<form action="agregarJugador" method="POST" class="my-4">
    <div class="row">
        <div>
            <div class="form-group">
                <label>Nombre del Jugador</label>
                <input required name="nombre_jugador" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label>Posicion</label>
                <input required name="posicion" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label>kd</label>
                <input required name="kd" type="number" class="form-control">
            </div>
            <div class="form-group">
                <label>Ingrese el id del equipo</label>
                <input required name="fk_equipo" type="number" class="form-control">
            </div>
            <div>
                <button type="submit" class="btn btn-outline-success d-grid gap-2 col-6 mx-auto my-4">Agregar</button>
            </div>
        </div>
    </div>
</form>