<form action="agregarJugador" method="POST" class="my-4">
    <div class="row">
        <div>
            <div class="form-group">
                <label>Nombre del Jugador</label>
                <input required name="nombre_jugador" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label>Posicion</label>
                <input required name="posicion" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label>kd</label>
                <input required name="kd" type="number" class="form-control">
            </div>
            <div class="form-group">
                <label>Equipo</label>
                <select required name="fk_equipo" class="form-control">
                    <option value="">Seleccione un equipo</option>
                    <?php foreach ($equipos as $equipo): ?>
                        <option value="<?= $equipo->id_equipo ?>"><?= $equipo->nombre_equipo ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div>
                <button type="submit" class="btn btn-outline-success d-grid gap-2 col-6 mx-auto my-4">Agregar</button>
            </div>
        </div>
    </div>
</form>