<?php require 'app/templates/header.phtml'; ?>

<form action="agregar" method="POST" enctype="multipart/form-data" class="my-4">
    <div class="row">
        <div>
            <div class="form-group">
                <label>Nombre del equipo</label>
                <input required name="nombre_equipo" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label>Ranking del equipo</label>
                <input required name="ranking" type="number" class="form-control">
            </div>
            <div class="form-group">
                <label>Región</label>
                <select required name="region" class="form-control">
                    <option value="">Selecciona una región</option>
                    <option value="EU">Europa (EU)</option>
                    <option value="SA">Sudamérica (SA)</option>
                    <option value="AS">Asia (AS)</option>
                    <option value="NA">Norteamérica (NA)</option>
                    <option value="OTRA">Otra</option>
                </select>
            </div>
            <div class="form-group">
                <label>Subir imagen del equipo</label>
                <input required name="equipo_imagen" type="file" accept="image/*" class="form-control">
            </div>
            <div>
                <button type="submit" class="btn btn-outline-success d-grid gap-2 col-6 mx-auto my-4">Guardar</button>
            </div>
        </div>
    </div>
</form>